// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3jwSKA43a2G45UCvyAFsMvJcZDZgWzMc',
    appId: '1:296405864288:web:bdfda9602f37fa78281805',
    messagingSenderId: '296405864288',
    projectId: 'alga-crm-system',
    authDomain: 'alga-crm-system.firebaseapp.com',
    databaseURL: 'https://alga-crm-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alga-crm-system.appspot.com',
    measurementId: 'G-CCDS69H38F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkL9unKd49eqk2yZ4-cS_pYrUA4OH2oro',
    appId: '1:296405864288:android:01d70f245f07a8ab281805',
    messagingSenderId: '296405864288',
    projectId: 'alga-crm-system',
    databaseURL: 'https://alga-crm-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alga-crm-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-SA0EMNRGUb3sRTBVGLFuXZNrvYpYn1w',
    appId: '1:296405864288:ios:da5297612682d891281805',
    messagingSenderId: '296405864288',
    projectId: 'alga-crm-system',
    databaseURL: 'https://alga-crm-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alga-crm-system.appspot.com',
    iosBundleId: 'com.example.mobileAlgaCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-SA0EMNRGUb3sRTBVGLFuXZNrvYpYn1w',
    appId: '1:296405864288:ios:7522ca83468509d6281805',
    messagingSenderId: '296405864288',
    projectId: 'alga-crm-system',
    databaseURL: 'https://alga-crm-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'alga-crm-system.appspot.com',
    iosBundleId: 'com.example.mobileAlgaCrm.RunnerTests',
  );
}
